## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
server:
  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true
  config:
    repositories: |
      - type: git
        url: https://github.com/ikamd0712/argocd-app-of-app.git
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
  additionalApplications: 
    - name: argocd
      namespace: argo-cd
      destination:
        namespace: argo-cd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ../values-override.yaml
        path: argocd-install/argo-cd
        repoURL: https://github.com/ikamd0712/argocd-app-of-app.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
    - name: argocd-apps
      namespace: argo-cd
      destination:
        namespace: argo-cd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-apps
        repoURL: https://github.com/ikamd0712/argocd-app-of-app.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: jenkins
      namespace: argo-cd
      destination:
        namespace: argo-cd
        server: https://kubernetes.default.svc
      project: argocd
      ignoreDifferences:
      - group: ''
        jsonPointers:
        - /data/jenkins-admin-password
        kind: Secret
      source:
        path: jenkins/
        repoURL: 
          - https://github.com/ikamd0712/argocd-app-of-app.git
          - https://github.com/jenkinsci/jenkins
          - https://github.com/jenkinsci/docker-inbound-agent
          - https://github.com/maorfr/kube-tasks
          - https://github.com/jenkinsci/configuration-as-code-plugin
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
    - name: argocd-appprojects
      namespace: argo-cd
      destination:
        namespace: argo-cd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-appprojects
        repoURL: https://github.com/ikamd0712/argocd-app-of-app.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
  additionalProjects: 
  - name: argocd
    namespace: argo-cd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argo-cd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
